config/routes.rb
Teste::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :livros

  root :to => "livros#index"

end

app/models/livro.rb
class Livro < ActiveRecord::Base
  attr_accessible :titulo, :autor, :isbn, :descricao
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
  before_filter :login_required
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  def index
    @livros = Livro.all
  end

  def show
    @livro = Livro.find(params[:id])
  end

  def new
    @livro = Livro.new
  end

  def create
    @livro = Livro.new(params[:livro])
    if @livro.save
      redirect_to @livro, :notice => "Successfully created livro."
    else
      render :action => 'new'
    end
  end

  def edit
    @livro = Livro.find(params[:id])
  end

  def update
    @livro = Livro.find(params[:id])
    if @livro.update_attributes(params[:livro])
      redirect_to @livro, :notice  => "Successfully updated livro."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @livro = Livro.find(params[:id])
    @livro.destroy
    redirect_to livros_url, :notice => "Successfully destroyed livro."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :login_required, :only => [:new, :create]
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #skip_before_filter :login_required, :only => [:new, :create]

  before_filter :login_required, :except => [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if logged_in? %>
      Welcome <%= current_user.username %>.
      <%= link_to "Edit profile", edit_current_user_path %> or
      <%= link_to "Log out", logout_path %>
    <% else %>
      <%= link_to "Sign up", signup_path %> or
      <%= link_to "log in", login_path %>.
    <% end %>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_for @livro do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </p>
  <p>
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </p>
  <p>
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/livros/edit.html.erb
<% title "Edit Livro" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @livro %> |
  <%= link_to "View All", livros_path %>
</p>

app/views/livros/index.html.erb
<% title "Livros" %>

<table>
  <tr>
    <th>Titulo</th>
    <th>Autor</th>
    <th>Isbn</th>
    <th>Descricao</th>
  </tr>
  <% for livro in @livros %>
    <tr>
      <td><%= livro.titulo %></td>
      <td><%= livro.autor %></td>
      <td><%= livro.isbn %></td>
      <td><%= livro.descricao %></td>
      <td><%= link_to "Show", livro %></td>
      <td><%= link_to "Edit", edit_livro_path(livro) %></td>
      <td><%= link_to "Destroy", livro, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Livro", new_livro_path %></p>

app/views/livros/new.html.erb
<% title "New Livro" %>

<%= render 'form' %>

<p><%= link_to "Back to List", livros_path %></p>

app/views/livros/show.html.erb
<% title "Livro" %>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>
<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>
<p>
  <strong>Isbn:</strong>
  <%= @livro.isbn %>
</p>
<p>
  <strong>Descricao:</strong>
  <%= @livro.descricao %>
</p>

<p>
  <%= link_to "Edit", edit_livro_path(@livro) %> |
  <%= link_to "Destroy", @livro, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", livros_path %>
</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>